[gossip]
    entrypoints = [
        "entrypoint.devnet.solana.com:8001",
        "entrypoint2.devnet.solana.com:8001",
        "entrypoint3.devnet.solana.com:8001",
    ]
[consensus]
    expected_genesis_hash = "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG"
